title: "Susanna Wirthgen"
description: "PhD researcher (Political Science) Â· DYNAMICS RTG (HU Berlin & Hertie School)"
theme: minima

minima:
  skin: auto

header_pages:
  - research.md
  - teaching.md
  - cv.md

# Optional: makes URLs cleaner
permalink: pretty
